const url = `https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/`;
export const products = [
  {
    id: 1,
    name: "EA7",
    description: "EA7 Bisiklet Yaka Siyah Erkek T-Shirt ",
    price: 85,
    image: [`${url}5003143700_001_01.jpg`],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: true,
  },
  {
    id: 2,
    name: "EA7",
    description: "EA7 Bisiklet Yaka Beyaz Erkek T-Shirt",
    price: 85,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003143664_100_01.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: false,
  },
  {
    id: 3,
    name: "EA7",
    description: "EA7 Beyaz Erkek Polo T-Shirt ",
    price: 95,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003156861_100_04.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: true,
  },
  {
    id: 4,
    name: "EA7",
    description: "EA7 Kapüşon Yaka Siyah Erkek Sweatshırt ",
    price: 95,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003106403_001_01.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: false,
  },
  {
    id: 1,
    name: "EA7",
    description: "EA7 Bisiklet Yaka Siyah Erkek T-Shirt ",
    price: 85,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003143700_001_01.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: true,
  },
  {
    id: 2,
    name: "EA7",
    description: "EA7 Bisiklet Yaka Beyaz Erkek T-Shirt",
    price: 85,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003143664_100_01.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: false,
  },
  {
    id: 3,
    name: "EA7",
    description: "EA7 Beyaz Erkek Polo T-Shirt ",
    price: 95,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003156861_100_04.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: true,
  },
  {
    id: 4,
    name: "EA7",
    description: "EA7 Kapüşon Yaka Siyah Erkek Sweatshırt ",
    price: 95,
    image: [
      "https://raw.githubusercontent.com/mehmetulker/ecommerce_api/main/men/5003106403_001_01.jpg",
    ],
    sizes: ["M", "S", "XL", "XXL"],
    category: "Men",
    subCategory: "TopWear",
    bestseller: false,
  },
];
